### ISSUE TITLE
Toggle component setting value to empty string

### ISSUE THREAD

**Issue by alexlukelevy** [erikras/redux-form-material-ui#153] opened 2017-06-01 15:24 UTC
I have a very simple Toggle field which is being initalised to to `true`. When I click the toggle the value is being changed to `""` in the redux store. It will flip back and forth between `true` and `""` as you click the toggle. I expected it to flip between `true` and `false`, is this not the case?

```
// in my form
<Field name="toggle" component={Toggle} />

...

// props passed to redux-form decorated component
{
  initialValues: {
    toggle: true
  }
}
```

redux-form-material-ui@4.2.0
redux-form@6.7.0
material-ui@0.17.4

**Comment by erback** [comment] 2017-06-12 07:36
I can confirm the same issue here, did you manage to solve it @alexlukelevy ? The strange thing is that it seems to work as expected for me in my dev environment on my local computer but not when I compress the code for production. Make me think that this might have to do with webpack somehow.

**Comment by kgram** [comment] 2017-06-12 07:37
I have this same problem. As a temporary workaround, pass `parse={Boolean}` to your `Field`.

I don't think this is an error in redux-form-material-ui, it seems to stem from [this line](https://github.com/erikras/redux-form/blob/v6.8.0/src/events/getValue.js#L30) in redux-form. I'll create an issue there.

**Comment by kgram** [comment] 2017-06-12 07:52
It seems this is [deliberate behaviour introduced by redux-form](https://github.com/erikras/redux-form/pull/2863). Why I cannot say, their arguments make no sense to me, I would always want a boolean to be a boolean, I cannot imagine anyone wants a `true`/`''` boolean.

Anyways, the `parse={Boolean}` trick should work. `normalize` could probably be used as well. If this can be fixed in redux-form-material-ui, maybe with a default normalizer or something, that would probably be best.

@erback: The reason it works for you in test is that this "fix" was recently released as a minor version. You are probably running an older version on your own machine, if you reinstall your dependencies you will get the breaking version as well.

**Comment by erback** [comment] 2017-06-12 10:31
@kgram that explains things! Your temp fix is good enough for me now at least, thanks a lot!

**Closed** 2022-04-26 15:44 UTC
