### ISSUE TITLE
Support for Material UI V1 

### ISSUE THREAD

**Issue by diecastro** [erikras/redux-form-material-ui#175] opened 2017-09-01 15:56 UTC
Hi there, any possibility for this ?  Getting some errors due to missing dependencies 

Thanks in advance!

**Comment by tatemz** [comment] 2017-09-04 15:35
Duplicate of #165

**Comment by mihirsoni** [comment] 2017-09-12 16:01
Closing this and tracking here #165

**Closed by mihirsoni** 2017-09-12 16:01 UTC
